### ISSUE TITLE
How to split the content information c and style s from the embedding z of  input x?

### ISSUE THREAD

**Issue by Siki-cloud** [hanqi-qi/Matte_Multi-domain-Counterfactual-Generation-with-identifiability-guarantee#1]
such a great work MaTTE is！Thank you !

I am currently exploring the project's codebase,  cause I am confused by the observation of c and s, and the explanation in the paper seems to be limited :

> We split z into two components: c and s. As shown in Fig 1, both c and s encompass information of a particular domain u, and s is also influenced by c. We parameterize such influences using flow-based models [Dolatabadi et al., 2020, Durkan et al., 2019] rc and rs, respectively: ˜c = rc(c; u), s˜ = rs(s; u, c),  (5) 

This description made me confused about how to  getting c and s from z.  I`am sorry I cannot find the implement details in the codebase.  Could you kindly provide guidance on where in the codebase I can find the relevant code for this?  Any pointers or file paths would be greatly appreciated.

**Comment by hanqi-qi** [comment]
Thanks for your interest to our work.
We split z into two components, c and s by implementing as follows, where c_dim is the predefined content dimension, and the remaining dimensions are s_dim = z_dim-c_dim. Details can be found in [influential_vae.py](https://github.com/hanqi-qi/Matte/blob/main/models/influential_vae.py)
z1 = z[:,:self.c_dim]
z2 = z[:,self.c_dim:]

**Comment by Siki-cloud** [comment]
Thank you so much！
